# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-KO-Hangul-Util
version:      0.23
version_from: Util.pm
installdirs:  site
requires:
    Carp:                          0
    charnames:                     0
    constant:                      0
    DynaLoader:                    0
    Exporter:                      0
    File::Copy:                    0
    strict:                        0
    Test:                          0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
